// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProtocol.proto

package protocol;

public final class MessageProtocol {
  private MessageProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Protocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 messageId = 1;</code>
     */
    long getMessageId();

    /**
     * <code>.protocol.Protocol.headType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.protocol.Protocol.headType type = 2;</code>
     */
    protocol.MessageProtocol.Protocol.headType getType();

    /**
     * <code>bytes body = 3;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code protocol.Protocol}
   */
  public  static final class Protocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Protocol)
      ProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Protocol.newBuilder() to construct.
    private Protocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Protocol() {
      messageId_ = 0L;
      type_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Protocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.MessageProtocol.internal_static_protocol_Protocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.MessageProtocol.internal_static_protocol_Protocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.MessageProtocol.Protocol.class, protocol.MessageProtocol.Protocol.Builder.class);
    }

    /**
     * Protobuf enum {@code protocol.Protocol.headType}
     */
    public enum headType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN = 0;</code>
       */
      LOGIN(0),
      /**
       * <code>LOGOUT = 1;</code>
       */
      LOGOUT(1),
      /**
       * <code>AUTHENTICATED = 2;</code>
       */
      AUTHENTICATED(2),
      /**
       * <code>HTTP_REQUEST = 3;</code>
       */
      HTTP_REQUEST(3),
      /**
       * <code>HTTP_RESPONSE = 4;</code>
       */
      HTTP_RESPONSE(4),
      /**
       * <code>PUSH = 5;</code>
       */
      PUSH(5),
      /**
       * <code>PING = 6;</code>
       */
      PING(6),
      /**
       * <code>PONG = 7;</code>
       */
      PONG(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>LOGIN = 0;</code>
       */
      public static final int LOGIN_VALUE = 0;
      /**
       * <code>LOGOUT = 1;</code>
       */
      public static final int LOGOUT_VALUE = 1;
      /**
       * <code>AUTHENTICATED = 2;</code>
       */
      public static final int AUTHENTICATED_VALUE = 2;
      /**
       * <code>HTTP_REQUEST = 3;</code>
       */
      public static final int HTTP_REQUEST_VALUE = 3;
      /**
       * <code>HTTP_RESPONSE = 4;</code>
       */
      public static final int HTTP_RESPONSE_VALUE = 4;
      /**
       * <code>PUSH = 5;</code>
       */
      public static final int PUSH_VALUE = 5;
      /**
       * <code>PING = 6;</code>
       */
      public static final int PING_VALUE = 6;
      /**
       * <code>PONG = 7;</code>
       */
      public static final int PONG_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static headType valueOf(int value) {
        return forNumber(value);
      }

      public static headType forNumber(int value) {
        switch (value) {
          case 0: return LOGIN;
          case 1: return LOGOUT;
          case 2: return AUTHENTICATED;
          case 3: return HTTP_REQUEST;
          case 4: return HTTP_RESPONSE;
          case 5: return PUSH;
          case 6: return PING;
          case 7: return PONG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<headType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          headType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<headType>() {
              public headType findValueByNumber(int number) {
                return headType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.MessageProtocol.Protocol.getDescriptor().getEnumTypes().get(0);
      }

      private static final headType[] VALUES = values();

      public static headType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private headType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.Protocol.headType)
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private long messageId_;
    /**
     * <code>int64 messageId = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.protocol.Protocol.headType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.protocol.Protocol.headType type = 2;</code>
     */
    public protocol.MessageProtocol.Protocol.headType getType() {
      @SuppressWarnings("deprecation")
      protocol.MessageProtocol.Protocol.headType result = protocol.MessageProtocol.Protocol.headType.valueOf(type_);
      return result == null ? protocol.MessageProtocol.Protocol.headType.UNRECOGNIZED : result;
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 3;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0L) {
        output.writeInt64(1, messageId_);
      }
      if (type_ != protocol.MessageProtocol.Protocol.headType.LOGIN.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(3, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageId_);
      }
      if (type_ != protocol.MessageProtocol.Protocol.headType.LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.MessageProtocol.Protocol)) {
        return super.equals(obj);
      }
      protocol.MessageProtocol.Protocol other = (protocol.MessageProtocol.Protocol) obj;

      boolean result = true;
      result = result && (getMessageId()
          == other.getMessageId());
      result = result && type_ == other.type_;
      result = result && getBody()
          .equals(other.getBody());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.MessageProtocol.Protocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.MessageProtocol.Protocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.MessageProtocol.Protocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.MessageProtocol.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.MessageProtocol.Protocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Protocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Protocol)
        protocol.MessageProtocol.ProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.MessageProtocol.internal_static_protocol_Protocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.MessageProtocol.internal_static_protocol_Protocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.MessageProtocol.Protocol.class, protocol.MessageProtocol.Protocol.Builder.class);
      }

      // Construct using protocol.MessageProtocol.Protocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0L;

        type_ = 0;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.MessageProtocol.internal_static_protocol_Protocol_descriptor;
      }

      @java.lang.Override
      public protocol.MessageProtocol.Protocol getDefaultInstanceForType() {
        return protocol.MessageProtocol.Protocol.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.MessageProtocol.Protocol build() {
        protocol.MessageProtocol.Protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.MessageProtocol.Protocol buildPartial() {
        protocol.MessageProtocol.Protocol result = new protocol.MessageProtocol.Protocol(this);
        result.messageId_ = messageId_;
        result.type_ = type_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.MessageProtocol.Protocol) {
          return mergeFrom((protocol.MessageProtocol.Protocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.MessageProtocol.Protocol other) {
        if (other == protocol.MessageProtocol.Protocol.getDefaultInstance()) return this;
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.MessageProtocol.Protocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.MessageProtocol.Protocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long messageId_ ;
      /**
       * <code>int64 messageId = 1;</code>
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>int64 messageId = 1;</code>
       */
      public Builder setMessageId(long value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.protocol.Protocol.headType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.protocol.Protocol.headType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Protocol.headType type = 2;</code>
       */
      public protocol.MessageProtocol.Protocol.headType getType() {
        @SuppressWarnings("deprecation")
        protocol.MessageProtocol.Protocol.headType result = protocol.MessageProtocol.Protocol.headType.valueOf(type_);
        return result == null ? protocol.MessageProtocol.Protocol.headType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.Protocol.headType type = 2;</code>
       */
      public Builder setType(protocol.MessageProtocol.Protocol.headType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Protocol.headType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 3;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 3;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 3;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Protocol)
    }

    // @@protoc_insertion_point(class_scope:protocol.Protocol)
    private static final protocol.MessageProtocol.Protocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.MessageProtocol.Protocol();
    }

    public static protocol.MessageProtocol.Protocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Protocol>
        PARSER = new com.google.protobuf.AbstractParser<Protocol>() {
      @java.lang.Override
      public Protocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Protocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Protocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Protocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.MessageProtocol.Protocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Protocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Protocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MessageProtocol.proto\022\010protocol\"\317\001\n\010Pr" +
      "otocol\022\021\n\tmessageId\030\001 \001(\003\022)\n\004type\030\002 \001(\0162" +
      "\033.protocol.Protocol.headType\022\014\n\004body\030\003 \001" +
      "(\014\"w\n\010headType\022\t\n\005LOGIN\020\000\022\n\n\006LOGOUT\020\001\022\021\n" +
      "\rAUTHENTICATED\020\002\022\020\n\014HTTP_REQUEST\020\003\022\021\n\rHT" +
      "TP_RESPONSE\020\004\022\010\n\004PUSH\020\005\022\010\n\004PING\020\006\022\010\n\004PON" +
      "G\020\007B\033\n\010protocolB\017MessageProtocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_Protocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Protocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Protocol_descriptor,
        new java.lang.String[] { "MessageId", "Type", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
